### PR TITLE
Remove two un-needed feature gates

### PR DESCRIPTION
**Pull request by steveklabnik**
These two gates have stable alternatives already.

### CODE REVIEW

**Comment by Johnson-A** [comment]
Thanks for catching those!

**Comment by steveklabnik** [comment]
Any time. :)

**Comment by steveklabnik** [comment]
Oh, and as for the others: you can make it so that you only use bench on nightly, but since you're using slice patterns and associated consts, i didn't feel like it was worth the effort, since you'll stay on nightly anwyay.

**Comment by Johnson-A** [comment]
That's good to know! I would rather not have any unstable features to make it possible to compile with any version but those features are the most natural way to accomplish certain things. If you have any more suggestions just let me know!

**Pull request merged**
